apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: services
spec:
  replicas: 3
  persistence:
    storageClassName: standard
    storage: 1Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      queue_master_locator = min-masters
      disk_free_limit.absolute = 2GB
      default_user = guest
      default_pass = guest
      loopback_users.guest = false
  service:
    type: ClusterIP