apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: services
spec:
  replicas: 2
  persistence:
    storageClassName: standard
    storage: 1Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      queue_master_locator = min-masters
      disk_free_limit.absolute = 2GB
      management.tcp.port = 15672
      listeners.tcp.default = 5672
      default_user = user
      default_pass = password
      loopback_users.guest = false
  service:
    type: LoadBalancer
    ports:
      - name: amqp
        port: 5672
        targetPort: 5672
  initContainers:
  - name: create-rabbitmq-user
    image: rabbitmq:3-management
    command: ['sh', '-c', 'until rabbitmqctl await_startup; do sleep 5; done; rabbitmqctl add_user user password && rabbitmqctl set_user_tags user administrator && rabbitmqctl set_permissions -p / user ".*" ".*" ".*"']
    env:
    - name: RABBITMQ_ERLANG_COOKIE
      valueFrom:
        secretKeyRef:
          name: rabbitmq-erlang-cookie
          key: cookie
    volumeMounts:
    - name: rabbitmq-data
      mountPath: /var/lib/rabbitmq