services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    command: >
          sh -c "
          rabbitmq-server &
          sleep 10 &&
          rabbitmqctl add_vhost / &&
          rabbitmqctl add_user user password &&
          rabbitmqctl set_user_tags user user &&
          rabbitmqctl set_permissions -p / user '.*' '.*' '.*' &&
          rabbitmqctl add_user admin admin &&
          rabbitmqctl set_user_tags admin administrator &&
          rabbitmqctl set_permissions -p / admin '.*' '.*' '.*' &&
          rabbitmqctl stop &&
          rabbitmq-server
          "
  
  pool-manager:
    image: grupo4sdypp2024/tp-integrador-pool-manager:1.0.8
    container_name: "pool-manager"
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
      - POOL_RABBITMQ_HOST=${POOL_RABBITMQ_HOST}
      - POOL_RABBITMQ_PORT=${POOL_RABBITMQ_PORT}
      - POOL_RABBITMQ_USER=${POOL_RABBITMQ_USER}
      - POOL_RABBITMQ_PASSWORD=${POOL_RABBITMQ_PASSWORD}
      - CONSUME_RABBITMQ_HOST=${CONSUME_RABBITMQ_HOST}
      - CONSUME_RABBITMQ_PORT=${CONSUME_RABBITMQ_PORT}
      - CONSUME_RABBITMQ_USER=${CONSUME_RABBITMQ_USER} 
      - CONSUME_RABBITMQ_PASSWORD=${CONSUME_RABBITMQ_PASSWORD}
      - KEEP_ALIVE_SERVER_HOST=${KEEP_ALIVE_SERVER_HOST}
      - KEEP_ALIVE_SERVER_PORT=${KEEP_ALIVE_SERVER_PORT}
      - COORDINATOR_HOST=${COORDINATOR_HOST}
      - COORDINATOR_PORT=${COORDINATOR_PORT}

networks:
  my_network:
    driver: bridge