apiVersion: apps/v1
kind: Deployment
metadata:
  name: keepalive
  namespace: apps
  labels:
    app: keepalive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keepalive
  template:
    metadata:
      labels:
        app: keepalive
    spec:
      containers:
        - name: keepalive
          image: tp-integrador-keep-alive-server:1.0.0
          ports:
            - containerPort: 5001
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5001
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 5001
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
      resources:
        requests:
          memory: "128Mi"  # Reservar 128Mi para garantizar que no sea evictado fácilmente
          cpu: "250m"      # Reservar una pequeña cantidad de CPU
        limits:
          memory: "256Mi"  # Permitir que use hasta 256Mi en picos
          cpu: "500m"      # Permitir un uso de CPU más alto si lo necesita
