apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: ngrok
  labels:
    app: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: wernight/ngrok:latest
          command: ["/bin/sh", "-c", "ngrok config add-authtoken $NGROK_AUTH_TOKEN && ngrok start --config /etc/ngrok/ngrok.yml --all"]
          env:
            - name: NGROK_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ngrok-secret
                  key: authtoken
          volumeMounts:
            - name: ngrok-config
              mountPath: /etc/ngrok/ngrok.yml
              subPath: ngrok.yml
      volumes:
        - name: ngrok-config
          configMap:
            name: ngrok-config