apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: ngrok
  labels:
    app: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      initContainers:
        - name: init-ngrok
          image: wernight/ngrok:latest
          command: ["/bin/sh", "-c", "echo \"authtoken: $NGROK_AUTH_TOKEN\" > /home/ngrok/.ngrok2/ngrok.yml"]
          env:
            - name: NGROK_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ngrok-secret
                  key: authtoken
          volumeMounts:
            - name: ngrok-config
              mountPath: /home/ngrok/.ngrok2
      containers:
        - name: ngrok
          image: wernight/ngrok:latest
          command: ["ngrok", "start", "--config", "/home/ngrok/.ngrok2/ngrok.yml", "--all"]
          volumeMounts:
            - name: ngrok-config
              mountPath: /home/ngrok/.ngrok2
      volumes:
        - name: ngrok-config
          emptyDir: {}
