apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: ngrok
  labels:
    app: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
        - name: ngrok
          image: wernight/ngrok:latest
          env:
            - name: NGROK_CONFIG
              valueFrom:
                secretKeyRef:
                  name: ngrok-secret
                  key: ngrok-config
            - name: NGROK_DEBUG
              value: "true"
          ports:
            - containerPort: 5000
            - containerPort: 5001
            - containerPort: 5672
