apiVersion: v1
kind: Service
metadata:
  name: ngrok-service
  namespace: ngrok
spec:
  selector:
    app: ngrok
  ports:
    - name: coordinator
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: keepalive
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
  type: LoadBalancer