services:
  redis:
    image: redis/redis-stack:latest
    container_name: "redis"
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - my_network
    volumes:
      - redis_data:/data
    restart: always

  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network
    volumes:
      - /Services/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  rabbitmq-worker-pool:
    image: "rabbitmq:management"
    container_name: "rabbitmq-worker-pool"
    ports:
      - "5673:5673"
      - "15673:15672"
    networks:
      - my_network
    volumes:
      - /Services/worker-pool-rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_NODE_PORT=5673

  coordinator:
    image: grupo4sdypp2024/tp-integrador-coordinator
    container_name: "coordinator"
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
  
  keep-alive-server:
    image: grupo4sdypp2024/tp-integrador-keep-alive-server
    container_name: "keep-alive-server"
    ports:
      - "5001:5001"
    depends_on:
      - coordinator
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
  
  worker-pool:
    image: grupo4sdypp2024/tp-integrador-worker-pool
    container_name: "worker-pool"
    ports:
      - "5002:5002"
    depends_on:
      - coordinator
      - rabbitmq-worker-pool
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1

  # worker-1:
  #   image: grupo4sdypp2024/tp-integrador-worker
  #   container_name: "worker-1"
  #   depends_on:
  #     - coordinator
  #     - rabbitmq
  #     - redis
  #   networks:
  #     - my_network
  #   environment:
  #     - PYTHONUNBUFFERED=1

  # worker-2:
  #   image: grupo4sdypp2024/tp-integrador-worker
  #   container_name: "worker-2"
  #   depends_on:
  #     - coordinator
  #     - rabbitmq
  #     - redis
  #   networks:
  #     - my_network
  #   environment:
  #     - PYTHONUNBUFFERED=1

networks:
  my_network:
    driver: bridge

volumes:
  redis_data: