services:
  redis:
    image: redis/redis-stack:latest
    container_name: "redis"
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - my_network
    volumes:
      - redis_data:/data
    restart: always

  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network
    volumes:
      - /Services/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  coordinator:
    image: grupo4sdypp2024/tp-integrador-coordinator:1.0.4
    container_name: "coordinator"
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=localhost
      - REDIS_PORT=6739
      - REDIS_DB=0
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
  
  # keep-alive-server:
  #   image: grupo4sdypp2024/tp-integrador-keepalive:1.1.0
  #   container_name: "keep-alive-server"
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - coordinator
  #   networks:
  #     - my_network
  #   environment:
  #     - PYTHONUNBUFFERED=1
  
  worker-1:
    image: grupo4sdypp2024/tp-integrador-cpu-worker:1.0.2
    container_name: "worker-1"
    depends_on:
      - coordinator
      - rabbitmq
      - redis
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
      - COORDINATOR_HOST=localhost
      - COORDINATOR_PORT=5000
      - KEEPALIVE_HOST=localhost
      - KEEPALIVE_PORT=5001
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672

networks:
  my_network:
    driver: bridge

volumes:
  redis_data: