apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: traefik:v2.10
          args:
            - "--api.insecure=true"
            - "--providers.kubernetescrd"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.coordinator.address=:5000"
            - "--entrypoints.keepalive.address=:5001"
            - "--entrypoints.rabbitmq.address=:5672"
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 5000
            - containerPort: 5001
            - containerPort: 5672