apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: services
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - port: 8001
    targetPort: 8001
    name: redis-web
  selector:
    app: redis