services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redis_blocks"]
    restart: always
    
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network
    volumes:
      - ./Services/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  coordinator:
    image: grupo4sdypp2024/tp-integrador-coordinator
    container_name: "coordinator"
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - my_network

  worker-1:
    image: grupo4sdypp2024/tp-integrador-worker
    container_name: "worker-1"
    depends_on:
      - coordinator
      - rabbitmq
      - redis
    networks:
      - my_network
  
  worker-2:
    image: grupo4sdypp2024/tp-integrador-worker
    container_name: "worker-2"
    depends_on:
      - coordinator
      - rabbitmq
      - redis
    networks:
      - my_network

networks:
  my_network:
    driver: bridge