apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: coordinator
  type: ClusterIP
