apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: apps
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: coordinator
  type: ClusterIP
