apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: apps
  labels:
    app: coordinator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
        - name: coordinator
          image: grupo4sdypp2024/tp-integrador-coordinator:latest
          ports:
            - containerPort: 5000
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: coordinator-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: coordinator-config
                  key: RABBITMQ_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: coordinator-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: coordinator-config
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: coordinator-config
                  key: REDIS_DB
      resources:
        requests:
          memory: "128Mi"  # Reservar 128Mi para garantizar que no sea evictado fácilmente
          cpu: "250m"      # Reservar una pequeña cantidad de CPU
        limits:
          memory: "256Mi"  # Permitir que use hasta 256Mi en picos
          cpu: "500m"      # Permitir un uso de CPU más alto si lo necesita
