# Archivo de configuración Helm para Traefik. Este archivo se utiliza para personalizar la instalación de Traefik mediante el Helm chart oficial de Traefik.

ports:
  coordinator:
    expose: true
    port: 5000        # Puerto público de Traefik para Coordinator
    targetPort: 5000  # Puerto interno donde escucha Coordinator
    protocol: TCP
  keepalive:
    expose: true
    port: 5001        # Puerto público de Traefik para Keepalive
    targetPort: 5001  # Puerto interno donde escucha Keepalive
    protocol: TCP
  rabbitmq:
    expose: true
    port: 5672        # Puerto público de Traefik para RabbitMQ
    targetPort: 5672  # Puerto interno donde escucha RabbitMQ
    protocol: TCP

service:
  type: LoadBalancer
  spec:
    loadBalancerIP: "35.229.42.126"  # Reemplaza con tu IP estática regional

providers:
  kubernetesCRD: {}
  kubernetesIngress: {}

tcp:
  routers:
    coordinator-router:
      entryPoints:
        - coordinator
      service: coordinator-service
      rule: "HostSNI(*)"  # Acepta tráfico en el puerto 5000
    keepalive-router:
      entryPoints:
        - keepalive
      service: keepalive-service
      rule: "HostSNI(*)"  # Acepta tráfico en el puerto 5001
    rabbitmq-router:
      entryPoints:
        - rabbitmq
      service: rabbitmq-service
      rule: "HostSNI(*)"  # Acepta tráfico en el puerto 5672

  services:
    coordinator-service:
      loadBalancer:
        servers:
          - address: "coordinator.apps.svc.cluster.local:5000"  # Dirección interna del servicio Coordinator
    keepalive-service:
      loadBalancer:
        servers:
          - address: "keepalive.apps.svc.cluster.local:5001"  # Dirección interna del servicio KeepAlive
    rabbitmq-service:
      loadBalancer:
        servers:
          - address: "rabbitmq.services.svc.cluster.local:5672"  # Dirección interna del servicio RabbitMQ



# providers:
#   kubernetesCRD: {}
#   kubernetesIngress: {}

# entryPoints:
#   coordinator:
#     address: ":5000"  # Traefik escucha el tráfico externo en el puerto 5000
#   keepalive:
#     address: ":5001"  # Traefik escucha el tráfico externo en el puerto 5001
#   rabbitmq:
#     address: ":5672"  # Traefik escucha el tráfico externo en el puerto 5672

# tcp:
#   routers:
#     coordinator-router:
#       entryPoints:
#         - coordinator
#       service: coordinator-service
#       rule: "HostSNI(*)"  # Acepta cualquier tráfico en el puerto 5000
#     keepalive-router:
#       entryPoints:
#         - keepalive
#       service: keepalive-service
#       rule: "HostSNI(*)"  # Acepta cualquier tráfico en el puerto 5001
#     rabbitmq-router:
#       rule: "HostSNI(`*`)"
#       service: rabbitmq-service
#       entryPoints:
#         - rabbitmq

#   services:
#     coordinator-service:
#       loadBalancer:
#         servers:
#           - address: "coordinator.apps.svc.cluster.local:5000"  # Dirección interna del servicio Coordinator
#     keepalive-service:
#       loadBalancer:
#         servers:
#           - address: "keepalive.apps.svc.cluster.local:5001"  # Dirección interna del servicio KeepAlive
#     rabbitmq-service:
#       loadBalancer:
#         servers:
#           - address: "rabbitmq.default.svc.cluster.local:5672"  # Dirección interna del servicio RabbitMQ
            
# ingressClass:
#   enabled: true
#   isDefaultClass: true