apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "testuser"
        - name: POSTGRES_PASSWORD
          value: "testpassword"
        - name: POSTGRES_DB
          value: "exampledb"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: database
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: postgres-db
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/Guanart/SDyPP-2024-grupo-4.git
#     targetRevision: HEAD
#     path: TP-Integrador/manifests/database
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: database
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
