apiVersion: apps/v1
kind: Deployment
metadata:
  name: keepalive
  namespace: apps
  labels:
    app: keepalive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keepalive
  template:
    metadata:
      labels:
        app: keepalive
    spec:
      containers:
        - name: keepalive
          image: tp-integrador-keepalive:1.0.0
          ports:
            - containerPort: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
